# Generated by Django 3.2.9 on 2021-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='do_you_like_it',
            field=models.BooleanField(null=True, verbose_name='Do you like it?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='do_you_like_it',
            field=models.BooleanField(null=True, verbose_name='Do you like it?'),
        ),
    ]
