# Generated by Django 3.2.9 on 2021-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211123_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_of_publicity']},
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
